"""Fix issues with RBAC

Revision ID: 0f46a73fdb9b
Revises: a7e3e7c5e670
Create Date: 2024-12-15 23:42:37.712580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0f46a73fdb9b'
down_revision: Union[str, None] = 'a7e3e7c5e670'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sqlmodel.sql.sqltypes.AutoString(length=60), nullable=True))
    op.add_column('users', sa.Column('microsoft_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('users', sa.Column('microsoft_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), server_default='NOW()', nullable=False))
    op.drop_index('ix_users_email', table_name='users')
    op.create_unique_constraint(None, 'users', ['microsoft_id'])
    op.drop_column('users', 'jira_refresh_token')
    op.drop_column('users', 'email')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('jira_refresh_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'microsoft_token')
    op.drop_column('users', 'microsoft_id')
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
