"""Fix role-permission

Revision ID: 4eed6e79e00f
Revises: cb3c4a5e76f1
Create Date: 2024-12-29 02:27:47.430135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4eed6e79e00f'
down_revision: Union[str, None] = 'cb3c4a5e76f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('role_permissions', 'role_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('role_permissions', 'permission_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)

    # Create constraint primary key
    op.create_primary_key('pk_role_permissions', 'role_permissions', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('role_permissions', 'permission_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.alter_column('role_permissions', 'role_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    # ### end Alembic commands ###
