"""Added is_active, is_system_role to roles table

Revision ID: 6ee4eb19bab3
Revises: 899d729bcae4
Create Date: 2024-12-23 12:22:56.054580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6ee4eb19bab3'
down_revision: Union[str, None] = '899d729bcae4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column(
        'is_system_role', sa.Boolean(), nullable=False))
    op.add_column('roles', sa.Column(
        'is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'is_active')
    op.drop_column('roles', 'is_system_role')
    # ### end Alembic commands ###
