"""Create base model

Revision ID: 70ea455c38f1
Revises: 6f0cc2e7d012
Create Date: 2024-12-23 18:01:42.805867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '70ea455c38f1'
down_revision: Union[str, None] = '6f0cc2e7d012'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('permissions', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('role_permissions', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('role_permissions', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('role_permissions', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('roles', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('roles', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('roles', 'updated_at')
    op.drop_column('roles', 'created_at')
    op.drop_column('role_permissions', 'id')
    op.drop_column('role_permissions', 'updated_at')
    op.drop_column('role_permissions', 'created_at')
    op.drop_column('permissions', 'updated_at')
    op.drop_column('permissions', 'created_at')
    # ### end Alembic commands ###
