"""Remove id from role-permission

Revision ID: 782d472e6d24
Revises: 994d33969119
Create Date: 2024-12-29 02:47:08.260054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '782d472e6d24'
down_revision: Union[str, None] = '994d33969119'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('role_permissions', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('role_permissions', 'permission_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index('ix_role_permissions_id', table_name='role_permissions')
    op.drop_column('role_permissions', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role_permissions', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_index('ix_role_permissions_id', 'role_permissions', ['id'], unique=False)
    op.alter_column('role_permissions', 'permission_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('role_permissions', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
