"""Length config for microsoft_refresh_token

Revision ID: a184ff8e5c28
Revises: c958d22a953b
Create Date: 2024-11-23 15:45:33.927025

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = 'a184ff8e5c28'
down_revision: Union[str, None] = 'c958d22a953b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
