"""Add jira account id column

Revision ID: aacbb419595e
Revises: b08183af629b
Create Date: 2025-01-17 15:05:33.892488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'aacbb419595e'
down_revision: Union[str, None] = 'b08183af629b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('jira_account_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_index('ix_users_id', table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.drop_column('users', 'jira_account_id')
    # ### end Alembic commands ###
