"""Add microsoft_refresh_token

Revision ID: aefff01db3b6
Revises: 003b2377de38
Create Date: 2024-11-22 12:24:52.104978

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'aefff01db3b6'
down_revision: Union[str, None] = '003b2377de38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('microsoft_refresh_token', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'microsoft_refresh_token')
    # ### end Alembic commands ###
