"""generate all tables

Revision ID: b20d3cde6a83
Revises:
Create Date: 2025-04-05 14:19:33.725097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b20d3cde6a83'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_index(op.f('ix_permissions_id'), 'permissions', ['id'], unique=False)
    # op.create_index(op.f('ix_permissions_name'), 'permissions', ['name'], unique=True)
    # op.create_index(op.f('ix_projects_key'), 'projects', ['key'], unique=True)
    # op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=True)
    # op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True)
    # op.create_foreign_key(None, 'refresh_tokens', 'users', ['user_id'], ['id'])
    # op.create_foreign_key(None, 'role_permissions', 'roles', ['role_id'], ['id'])
    # op.create_foreign_key(None, 'role_permissions', 'permissions', ['permission_id'], ['id'])
    # op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    # op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    # op.create_index(op.f('ix_user_project_roles_id'), 'user_project_roles', ['id'], unique=False)
    # op.create_foreign_key(None, 'user_project_roles', 'users', ['user_id'], ['id'])
    # op.create_foreign_key(None, 'user_project_roles', 'projects', ['project_id'], ['id'])
    # op.create_foreign_key(None, 'user_project_roles', 'roles', ['role_id'], ['id'])
    # op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###
    pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_constraint(None, 'user_project_roles', type_='foreignkey')
    op.drop_constraint(None, 'user_project_roles', type_='foreignkey')
    op.drop_constraint(None, 'user_project_roles', type_='foreignkey')
    op.drop_index(op.f('ix_user_project_roles_id'), table_name='user_project_roles')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_constraint(None, 'role_permissions', type_='foreignkey')
    op.drop_constraint(None, 'role_permissions', type_='foreignkey')
    op.drop_constraint(None, 'refresh_tokens', type_='foreignkey')
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_index(op.f('ix_projects_key'), table_name='projects')
    op.drop_index(op.f('ix_permissions_name'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_id'), table_name='permissions')
    # ### end Alembic commands ###
