"""add project avatar url

Revision ID: b3e0f9785a18
Revises: b1e83a96aa83
Create Date: 2025-03-05 12:05:54.238528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b3e0f9785a18'
down_revision: Union[str, None] = 'b1e83a96aa83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('avatar_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_index('ix_projects_id', table_name='projects')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_projects_id', 'projects', ['id'], unique=False)
    op.drop_column('projects', 'avatar_url')
    # ### end Alembic commands ###
