"""Update user project role

Revision ID: c57a3821f8ff
Revises: 70ea455c38f1
Create Date: 2024-12-23 18:41:46.854124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c57a3821f8ff'
down_revision: Union[str, None] = '70ea455c38f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_project_roles', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.drop_column('user_project_roles', 'assigned_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_project_roles', sa.Column('assigned_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('user_project_roles', 'created_at')
    # ### end Alembic commands ###
