"""Length config for microsoft_refresh_token

Revision ID: c958d22a953b
Revises: aefff01db3b6
Create Date: 2024-11-23 15:42:34.906534

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = 'c958d22a953b'
down_revision: Union[str, None] = 'aefff01db3b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
