"""add user is_system_user

Revision ID: cdfde7e28953
Revises: b3e0f9785a18
Create Date: 2025-03-05 22:50:09.509805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cdfde7e28953'
down_revision: Union[str, None] = 'b3e0f9785a18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_system_user', sa.Boolean(), nullable=False, default=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_system_user')
    # ### end Alembic commands ###
