"""Add group to permission

Revision ID: ecf624488074
Revises: c57a3821f8ff
Create Date: 2024-12-29 00:14:34.901581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ecf624488074'
down_revision: Union[str, None] = 'c57a3821f8ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions', sa.Column('group', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('projects', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index('ix_projects_name', table_name='projects')
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=True)
    op.drop_column('role_permissions', 'updated_at')
    op.drop_column('role_permissions', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role_permissions', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('role_permissions', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.create_index('ix_projects_name', 'projects', ['name'], unique=False)
    op.alter_column('projects', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('permissions', 'group')
    # ### end Alembic commands ###
