name: Build and Deploy zODC Backend

on:
  push:
    branches:
      - main
      - dev

jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: |
          podman login docker.io \
            --username ${{ secrets.DOCKERHUB_USER }} \
            --password ${{ secrets.DOCKERHUB_TOKEN }}
        if: github.event_name != 'pull_request'

      - name: Build Image
        run: |
          podman build -t docker.io/${{ secrets.DOCKERHUB_USER }}/zodc-backend:latest .
          if [[ ${{ github.ref }} == refs/heads/* ]]; then
            podman tag docker.io/${{ secrets.DOCKERHUB_USER }}/zodc-backend:latest \
              docker.io/${{ secrets.DOCKERHUB_USER }}/zodc-backend:${{ github.ref_name }}
          fi

      - name: Push Image
        if: github.event_name != 'pull_request'
        run: |
          podman push docker.io/${{ secrets.DOCKERHUB_USER }}/zodc-backend:latest
          if [[ ${{ github.ref }} == refs/heads/* ]]; then
            podman push docker.io/${{ secrets.DOCKERHUB_USER }}/zodc-backend:${{ github.ref_name }}
          fi
