name: Build and Deploy zODC Backend

on:
  push:
    branches:
      - main
env:
  SERVICE_NAME: zodc-service-auth
  VERSION: 0.1.1
  REGISTRY_PROJECT: zodc

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up secrets directory
        run: |
          mkdir -p secrets
          echo "${{ secrets.JWT_PRIVATE_KEY }}" | base64 -d > secrets/jwt-private.pem
          echo "${{ secrets.JWT_PUBLIC_KEY }}" | base64 -d > secrets/jwt-public.pem
          chmod 600 secrets/jwt-private.pem secrets/jwt-public.pem

      - name: Build Image
        run: |
          docker build -t ${{ secrets.REGISTRY_HOST }}/${{ env.REGISTRY_PROJECT }}/${{ env.SERVICE_NAME }}:${{ env.VERSION }} .

      - name: Login to Docker Registry
        run: |
          echo ${{ secrets.REGISTRY_PASSWORD }} | docker login ${{ secrets.REGISTRY_HOST }} -u ${{ secrets.REGISTRY_USER }} --password-stdin

      - name: Push Image
        run: |
          docker push ${{ secrets.REGISTRY_HOST }}/${{ env.REGISTRY_PROJECT }}/${{ env.SERVICE_NAME }}:${{ env.VERSION }}
