name: Build and Deploy zODC Backend

on:
  push:
    branches:
      - main
      - dev
env:
  SERVICE_NAME: zodc-backend
  VERSION: 0.1.0

jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Image
        run: |
          docker build -t ${secrets.REGISTRY_HOST}:${secrets.REGISTRY_PORT}/${secrets.REGISTRY_USER}/${SERVICE_NAME}:${VERSION} .
          if [[ ${{ github.ref }} == refs/heads/* ]]; then
            docker tag ${secrets.REGISTRY_HOST}:${secrets.REGISTRY_PORT}/${secrets.REGISTRY_USER}/${SERVICE_NAME}:${VERSION} ${secrets.REGISTRY_HOST}:${secrets.REGISTRY_PORT}/${secrets.REGISTRY_USER}/${SERVICE_NAME}:${{ github.ref_name }}
          fi

      - name: Login to Docker Registry
        run: |
          docker login ${secrets.REGISTRY_HOST}:${secrets.REGISTRY_PORT} -u ${secrets.REGISTRY_USER} -p ${secrets.REGISTRY_PASSWORD}

      - name: Push Image
        run: |
          docker push ${secrets.REGISTRY_HOST}:${secrets.REGISTRY_PORT}/${secrets.REGISTRY_USER}/${SERVICE_NAME}:${VERSION}
          if [[ ${{ github.ref }} == refs/heads/* ]]; then
            docker push ${secrets.REGISTRY_HOST}:${secrets.REGISTRY_PORT}/${secrets.REGISTRY_USER}/${SERVICE_NAME}:${{ github.ref_name }}
          fi
