name: Build and Deploy zODC Backend

on:
  push:
    branches:
      - main
      - dev
env:
  REGISTRY_USER: zodc
  REGISTRY_HOST: localhost
  REGISTRY_PORT: 5000

jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Image
        run: |
          podman build -t ${REGISTRY_HOST}:${REGISTRY_PORT}/${REGISTRY_USER}/zodc-backend:latest .
          if [[ ${{ github.ref }} == refs/heads/* ]]; then
            podman tag ${REGISTRY_HOST}:${REGISTRY_PORT}/${REGISTRY_USER}/zodc-backend:latest ${REGISTRY_HOST}:${REGISTRY_PORT}/${REGISTRY_USER}/zodc-backend:${{ github.ref_name }}
          fi

      - name: Push Image
        run: |
          podman push ${REGISTRY_HOST}:${REGISTRY_PORT}/${REGISTRY_USER}/zodc-backend:latest
          if [[ ${{ github.ref }} == refs/heads/* ]]; then
            podman push ${REGISTRY_HOST}:${REGISTRY_PORT}/${REGISTRY_USER}/zodc-backend:${{ github.ref_name }}
          fi
